/**
 * Created by ardani on 3/10/17.
 */
export const LOCATION_SET = 'LOCATION_SET'
export const MARKER_REQUEST = 'MARKER_REQUEST'
export const MARKER_SUCCESS = 'MARKER_SUCCESS'
export const MARKER_EMPTY = 'MARKER_EMPTY'
export const MARKER_FAIL = 'MARKER_FAIL'
export const MARKER_INFO_SHOW = 'MARKER_INFO_SHOW'
export const MARKER_INFO_TOGGLE = 'MARKER_INFO_TOGGLE'
export const MARKER_INFO_CLOSE = 'MARKER_INFO_CLOSE'
